### ISSUE TITLE
Multiple model save

### ISSUE THREAD

**Issue by ecommatrimony** [evan108108/RESTFullYii#119]
Hi Evan,
I am very new to both Yii framework and web services. I have set up RESTfullYii, and it working properly. But one of my controller's create method has multiple-model POST data, where in, once the main model(say Profile) is saved, the ID is used as FK in another model and assigned to the field by using $model->fk = $profileModel_id.

There are actually 4 dependent models which get their FK values from Profile model just created. My webapp works perfectly with this setup, but after implementing RESTFullYii, when i do a POST to the URL say http://localhost/rephost/api/profile/ 

The JSON looks like this:
{"relation_1":{"fieldname1" : "value1"...},"relation2":{....},...fields of profile model....}

The error which i am getting at the moment is, ModelofRelation1: {"profile_id":["Profile cannot be blank."]}...

the relation1 model's relations method has following mapping 
'profile' => array(self::BELONGS_TO, 'Profile', 'profile_id'),

Kindly provide me some solution, as i am really stuck with it for long time now, and i am running out of time on this.

Thanks in advance.,

**Comment by marneikaufmann** [comment]
I'm having the same problem, any solution?

**Comment by marneikaufmann** [comment]
Product.php
`public function relations()
{
	return array(
		'options'              => array(self::HAS_MANY, 'ProductOption', 'idProduct'),
	);
}`

ProductOption
`public function relations()
{
	return array(
		'idProduct0' => array(self::BELONGS_TO, 'Product', 'idProduct'),
	);
}`

ProductController
`class ProductController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			array(
				'ext.starship.RestfullYii.filters.ERestFilter + 
				REST.GET, REST.PUT, REST.POST, REST.DELETE, REST.OPTIONS'
			),
		);
	}

	public function actions()
	{
		return array(
			'REST.'=>'ext.starship.RestfullYii.actions.ERestActionProvider',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', 'actions'=>array('REST.GET', 'REST.PUT', 'REST.POST', 'REST.DELETE', 'REST.OPTIONS'),
			'users'=>array('*'),
			),
			array('deny',  // deny all users
			'users'=>array('*'),
			),
		);
	}

	public function restEvents()
	{
		$this->onRest('produto.filter.req.auth.ajax.user', function($validation) {
			if(!$validation) {
				return false;
			}
			switch ($this->getAction()->getId()) {
				case 'REST.POST':
					return Yii::app()->user->checkAccess('REST-CREATE');
					break;
				case 'REST.PUT':
					return Yii::app()->user->checkAccess('REST-UPDATE');
					break;
				case 'REST.DELETE':
					return Yii::app()->user->checkAccess('REST-DELETE');
					break;
				default:
					return false;
					break;
			}
		});

		$this->onRest('model.with.relations', function($model) {
			return array('options');
		});

		$this->onRest('req.post.resource.render', function($model, $relations=array('options'), $visibleProperties=[], $hiddenProperties=[]) {
			$this->renderJSON([
				'type'              => 'rest',
				'success'           => 'true',
				'message'           => "Record Created",
				'totalCount'    => "1",
				'modelName'     => get_class($model),
				'relations'     => $relations,
				'visibleProperties' => $visibleProperties,
				'hiddenProperties'  => $hiddenProperties,
				'data'              => $model,
			]);
		});

		$this->onRest('req.put.resource.render', function($model, $relations=array('options'), $visibleProperties=[], $hiddenProperties=[]) {
			$this->renderJSON([
				'type'              => 'rest',
				'success'           => 'true',
				'message'           => "Record Updated",
				'totalCount'    => "1",
				'modelName'     => get_class($model),
				'relations'     => $relations,
				'visibleProperties' => $visibleProperties,
				'hiddenProperties'  => $hiddenProperties,
				'data'              => $model,
			]);
		});
	}
}`

The JSON looks like this:
`{'name': 'T-shirt','price': '100.00', 'options': [{'name':'Color'},{'name': 'Size'}]}`

The error which i am getting at the moment is:
`{
        "success": false,
        "message": "Could not save Model: ProductOption: {"idProduct":["Product cannot be blank."]}",
        "data":
        {
            "errorCode": 500,
            "message": "Could not save Model: ProductOption : {"idProduct":["Product cannot be blank."]}"
        }
    }`
