### ISSUE TITLE
handling MANY_MANY put request for sub-resources

### ISSUE THREAD

**Issue by kaushikkapil** [evan108108/RESTFullYii#147]
@evan108108 
Suppose I have two tables "question" and "test". Now, I have a mapping table "test_question_mapping", with the following structure:

```
-------------------------------------------
|  id    |   test_id   |   question_id   |
-------------------------------------------
```

For a test, the question is now a subresource, and I am able to call the standard RESTfull APIs on top of it, and corresponding entries get added to the mapping table. Everything works just as expected !

However, I run into some problems if I want to store some additional information in the mapping table, for e.g.:

```
--------------------------------------------------------------
|  id    |   test_id   |   question_id   |    is_optional  |   
--------------------------------------------------------------
```

Here, at the time of adding the question to test, I want to say whether it is mandatory or optional to answer that question in this test. In this case, when I try the sub-resource "PUT" API with RESTfullYii, I see that a new row is inserted, but the "is_optional" field is not added. How can I solve this problem? Kindly suggest.

Regards,
Kapil

**Comment by Maykonn** [comment]
@evan108108, it does not work for HAS_MANY or HAS_ONE relations? See #195
