### ISSUE TITLE
Access for guests

### ISSUE THREAD

**Issue by nicdnepr** [evan108108/RESTFullYii#174]
Hi. How can i allow access for anonymous users? I added code 
>>array('allow', 'actions'=>array('REST.GET', 'REST.PUT', 'REST.POST', 'REST.DELETE', 'REST.OPTIONS'),
				'users'=>array('*'),
			),

but it's not work.

**Comment by jossemarGT** [comment]
+1

**Comment by evan108108** [comment]
@nicdnepr, @jossemarGT Just use the "post.filter.req.auth.user" to provide custom access using any logic that you would like:

```php
$this->onRest('post.filter.req.auth.user', function($validation) {
    return $validation; //Bool
});
```

**Comment by jossemarGT** [comment]
Thanks!
