### ISSUE TITLE
Apply filter on two relative tables

### ISSUE THREAD

**Issue by talhakazmi** [evan108108/RESTFullYii#175]
I have a table structure of friends, i have applied a filter
[{"property":"user_id","value":"x","operator":"="},{"property":"friends.friend_id","value":"x","operator":"="}]

This makes the query with AND in between these two conditions i need OR in between these two conditions. I have tried ANDOR but this works when conditions are for the same table.

Please help me out.

**Comment by talhakazmi** [comment]
Still couldn't find any solution, any one can help is this regard.

**Comment by evan108108** [comment]
@talhakazmi : Just use the "andor" filter property:

http://api/post?filter=[{"property":"author_id", "value":3, "operator":"=", "andor":"or"}, {"property":"author_id", "value":2, "operator":"=", "andor":"or"}]
