### ISSUE TITLE
Usage without urlFormat = 'path'

### ISSUE THREAD

**Issue by axelson** [evan108108/RESTFullYii#177]
Hi, I'm working with a legacy app that uses urlFormat = 'get' (the default) and thus the examples of querying `/api/work` do not work. If I do change my `urlManager` config to `urlFormat = 'path'` then the `/api/work` query works. However, if I remove that line from my config I would expect a url like `index.php?r=api/work` to work, however it does not. What query parameter do I need to use?

**Comment by kodeplusdev** [comment]
I also get this issue, and can not config with urlFormat = 'get' ... Please tell me how to do it.

**Comment by evan108108** [comment]
We do not support urlFormat = 'get'
