### ISSUE TITLE
Yii2

### ISSUE THREAD

**Issue by adantart** [evan108108/RESTFullYii#178]
Two problems in Yii2:

1) urlFormat => 'path' (in config)  has to be commented , if not , it does not load properly

2) when trying first attempt to use it, routes are not loaded properly.

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: yii\web\UrlRule::0

Is this extension working with Yii2 ?

Thank you

**Comment by evan108108** [comment]
Yii2 is not supported. Yii2 has some very nice built-in functionality very similar to RESTFullYii that you might want to try...
