### ISSUE TITLE
Filter is not working by case insensitive

### ISSUE THREAD

**Issue by Dhineshtyr** [evan108108/RESTFullYii#181]
@evan108108 

I'm trying to use filter on default API. 

ex : api/post/post/?filter[{'property':'title','value':'CaSe'}]

Filter is working for case sensitive. How to make it work for case insensitive.

**Comment by evan108108** [comment]
This is down to your database. This filter basically translates to 

```mysql
SELECT * FROM post WHERE title = "CaSe"
```

Now MYSQL queries are not case-sensitive by default so...
