### ISSUE TITLE
Error 404  Unable to resolve the request "api/series"

### ISSUE THREAD

**Issue by amjadsoftrove** [evan108108/RESTFullYii#184]
i've configured your extension, but now i m getting 404 for api/series.
I m using PHP Version 5.5.9-1ubuntu4.14

Following is the code of SeriesController.php

class SeriesController extends Controller
{
	public function filters()
	{
	    return array(
		'accessControl', // perform access control for CRUD operations
		array(
		    'RestfullYii.filters.ERestFilter +
		    REST.GET, REST.PUT, REST.POST, REST.DELETE, REST.OPTIONS'
		),
	    );
	}

	public function actions()
	{
	    return array(
		'REST.' => 'RestfullYii.actions.ERestActionProvider',
	    );
	}

	public function accessRules()
	{
	    return array(
		array('allow', 'actions' => array('REST.GET', 'REST.PUT', 'REST.POST', 'REST.DELETE', 'REST.OPTIONS'),
		    'users' => array('*'),
		),
		array('deny',
		    'users' => array('*'),
		),
	    );
	}
}

**Comment by evan108108** [comment]
Do you have your routes set up as shown in the Docs?
