### ISSUE TITLE
Multiple model save with relation HAS_MANY

### ISSUE THREAD

**Issue by marneikaufmann** [evan108108/RESTFullYii#190]
#119 I'm having the same problem, @evan108108 you can show an example to save multiple models related? MANY_MANY works perfectly, but HAS_MANY does not.

**Comment by evan108108** [comment]
@marneikaufmann :> If you can send me an example of exactly what you are trying to do and the error you are seeing that might help.

**Comment by marneikaufmann** [comment]
**Product.php**

`public function relations()
{
	return array(
		'options'              => array(self::HAS_MANY, 'ProductOption', 'idProduct'),
	);
}`



**ProductOption.php**

`public function relations()
{
	return array(
		'idProduto0' => array(self::BELONGS_TO, 'Produto', 'idProduto'),
	);
}`



**ProductController.php**

`class ProdutoController extends Controller
{
	public $layout='//layouts/column2';

	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			array(
				'ext.starship.RestfullYii.filters.ERestFilter + 
				REST.GET, REST.PUT, REST.POST, REST.DELETE, REST.OPTIONS'
			),
		);
	}

	public function actions()
	{
		return array(
			'REST.'=>'ext.starship.RestfullYii.actions.ERestActionProvider',
		);
	}

	public function accessRules()
	{
		return array(
			array('allow', 'actions'=>array('REST.GET', 'REST.PUT', 'REST.POST', 'REST.DELETE', 'REST.OPTIONS'),
			'users'=>array('*'),
			),
			array('deny',  // deny all users
			'users'=>array('*'),
			),
		);
	}

	public function restEvents()
	{
		$this->onRest('produto.filter.req.auth.ajax.user', function($validation) {
			if(!$validation) {
				return false;
			}
			switch ($this->getAction()->getId()) {
				case 'REST.POST':
					return Yii::app()->user->checkAccess('REST-CREATE');
					break;
				case 'REST.PUT':
					return Yii::app()->user->checkAccess('REST-UPDATE');
					break;
				case 'REST.DELETE':
					return Yii::app()->user->checkAccess('REST-DELETE');
					break;
				default:
					return false;
					break;
			}
		});

		$this->onRest('model.with.relations', function($model) {
			return array('options');
		});

		$this->onRest('model.find', function($model, $id) {
			$criteria=new CDbCriteria;
			$criteria->compare('id', $id);
			return $model->find($criteria);
		});

		$this->onRest('model.find.all', function($model) {
			$criteria=new CDbCriteria;
			return $model->findAll($criteria);
		});

		$this->onRest('model.save', function($model) {
			if(!$model->save())
			{
				throw new CHttpException('400', CJSON::encode($model->errors));
			}
			$model->refresh();
			return $model;
		});

		$this->onRest('model.delete', function($model) {
			throw new CHttpException('400', 'Not allowed');
		});

		$this->onRest('req.post.resource.render', function($model, $relations=array('options'), $visibleProperties=[], $hiddenProperties=[]) {
			$this->renderJSON([
				'type'              => 'rest',
				'success'           => 'true',
				'message'           => "Record Created",
				'totalCount'    => "1",
				'modelName'     => get_class($model),
				'relations'     => $relations,
				'visibleProperties' => $visibleProperties,
				'hiddenProperties'  => $hiddenProperties,
				'data'              => $model,
			]);
		});

		$this->onRest('req.put.resource.render', function($model, $relations, $visibleProperties=[], $hiddenProperties=[]) {
			$this->renderJSON([
				'type'              => 'rest',
				'success'           => 'true',
				'message'           => "Record Updated",
				'totalCount'    => "1",
				'modelName'     => get_class($model),
				'relations'     => $relations,
				'visibleProperties' => $visibleProperties,
				'hiddenProperties'  => $hiddenProperties,
				'data'              => $model,
			]);
		});
	}
}`



**The JSON looks like this:**
{'name': 't-shirt', 'price': '100.00', 'options': [{'name': 'Color'}, {'name': 'Size'}]}



**The error which i am getting at the moment is**
`"message": "Could not save Model: ProductOption : {"idProduct":["Product cannot be blank."]}"`

**Comment by evan108108** [comment]
You will need to make two requests. First post the "Product" without relations then post back the "options" when you have the ID's. 

Also since it does not appear that you are overriding any of the default RestEvents I think you can drop the "restEvents" method from your controller.

**Comment by marneikaufmann** [comment]
To MANY_MANY relationships I can send the same request, but for HAS_MANY relationship not ... right?

**Comment by evan108108** [comment]
Yes I believe MANY_MANY works with a single request but not so with
HAS_MANY...
