### ISSUE TITLE
Error is thrown when overriding model attributes with request's parameters

### ISSUE THREAD

**Issue by Maykonn** [evan108108/RESTFullYii#194]
The following warning is thrown when using the `ERestEvent::PRE_FILTER_MODEL_APPLY_PUT_DATA` or `ERestEvent::PRE_FILTER_MODEL_APPLY_POST_DATA`:

```
Missing argument 2 for ERestEventListenerRegistry::{closure}()
on line 836
```

What I'm trying to do it is: I have a param called `serial` on PUT or POST requests, but this param must be mapped to the model attribute called `serial_code` for example. My code looks alike the below code:

```PHP
$this->onRest(ERestEvent::PRE_FILTER_MODEL_APPLY_PUT_DATA, function($model, $data, $restricted_properties) {
    $mappedData = ['serial_code' => $data['serial']];
    return $this->getResourceHelper()->setModelAttributes($model, $mappedData, $restricted_properties);
});
```

**Comment by Maykonn** [comment]
It was solved make use of: 
`ERestEvent::MODEL_APPLY_PUT_DATA` and 
`ERestEvet::MODEL_APPLY_POST_DATA` 

instead of: 
`ERestEvent::PRE_FILTER_MODEL_APPLY_PUT_DATA` and 
`ERestEvent::PRE_FILTER_MODEL_APPLY_POST_DATA`.

I just don't understand what happens when using either `ERestEvent::PRE_FILTER_MODEL_APPLY_PUT_DATA` or `ERestEvent::PRE_FILTER_MODEL_APPLY_POST_DATA` that makes PHP thrown a warning.

**The code below solves this issue:**

```PHP
$mapResquestDataToModel = function($requestData) {
    return ['serial_code' => $requestData['serial']];
};

$this->onRest(ERestEvent::MODEL_APPLY_POST_DATA, function($model, $data, $restricted_properties) use ($mapResquestDataToModel) {
    return $this->getResourceHelper()->setModelAttributes($model, $mapResquestDataToModel($data), $restricted_properties);
});

$this->onRest(ERestEvent::MODEL_APPLY_PUT_DATA, function($model, $data, $restricted_properties) use ($mapResquestDataToModel) {
    return $this->getResourceHelper()->setModelAttributes($model, $mapResquestDataToModel($data), $restricted_properties);
});
```

**Comment by evan108108** [comment]
@Maykonn: you need to return this : [$model, $data, $restricted_properties]; 
Seems you are returning only the model.

Here is the pre filter def:

```php
$this->onRest('pre.filter.model.apply.put.data', function($model, $data, $restricted_properties) {
	return [$model, $data, $restricted_properties]; //Array [Object, Array, Array]
});
```

Does that make sense?

**Comment by Maykonn** [comment]
For sure @evan108108 , thanks by the reply!

What it works better in that case, make use of the `pre.filter.model.apply.put.data` or `model.apply.put.data`? 
Generally speaking, I need to create a mapping between what I'm retrieving from the request to the model attributes, because not necessarily the request attributes has the same name that is configured on the model.

**Comment by evan108108** [comment]
@Maykonn: You may want to user the "pre.filter" because it leaves the main implementation in place. I would just change the  "$data" to match the model and then let the apply work as intended. But, you really have the option.

**Comment by Maykonn** [comment]
Ok. Thanks, @evan108108 .
