### ISSUE TITLE
Sub-Resources on HAS_ONE or HAS_MANY not working

### ISSUE THREAD

**Issue by Maykonn** [evan108108/RESTFullYii#195]
I'm getting a 404 http status code when trying to access a route like that `GET > /api/authors/1/books` where 1 is the author with id 1. Therefore, I want to retrieve a list of all books written by the author with id 1. But I'm getting the 404.

The author->books is a HAS_MANY relation.

It's working perfectly on MANY_MANY relations. It is expected to work only with MANY_MANY relations?

**Comment by evan108108** [comment]
Sub-recourses only apply to MANY_MANY relations.

**Comment by Maykonn** [comment]
I'll find a workaround. Thanks, @evan108108
